<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use App\Models\StudentRegistration;
use App\Models\Parents;
use App\Notifications\PasswordResetNotification;

class User extends Authenticatable
{
    /** @use HasFactory<\Database\Factories\UserFactory> */
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        "name",
        "email",
        "password",
        "phone",
        "role",
        "level",
        "parent_id",
        "profile_photo_path",
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = ["password", "remember_token"];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            "email_verified_at" => "datetime",
            "password" => "hashed",
        ];
    }

    public function studentRegistration()
    {
        return $this->hasOne(StudentRegistration::class);
    }

    /**
     * Get the student profile if user is a student
     */
    public function student()
    {
        return $this->hasOne(Student::class);
    }

    /**
     * Get the instructor profile if user is an instructor
     */
    public function instructor()
    {
        return $this->hasOne(Instructor::class);
    }

    /**
     * Get the parent profile if user is a parent
     */
    public function parentProfile()
    {
        return $this->hasOne(ParentModel::class);
    }

    /**
     * Get courses taught by this instructor (if user is instructor)
     * @deprecated Use instructor()->courses() instead
     */
    public function taughtCourses()
    {
        return $this->hasMany(Course::class, "instructor_id");
    }

    /**
     * Get enrollments for this student (if user is student)
     * @deprecated Use student()->enrollments() instead
     */
    public function enrollments()
    {
        return $this->hasMany(Enrollment::class, "student_id");
    }

    /**
     * Get submissions for this student (if user is student)
     * @deprecated Use student()->submissions() instead
     */
    public function submissions()
    {
        return $this->hasMany(Submission::class, "student_id");
    }

    public function grades()
    {
        return $this->hasMany(Grade::class, "student_id");
    }

    public function gradedGrades()
    {
        return $this->hasMany(Grade::class, "graded_by");
    }

    public function parent()
    {
        return $this->belongsTo(Parents::class, "parent_id");
    }

    /**
     * Send the password reset notification.
     *
     * @param  string  $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new PasswordResetNotification($token));
    }

    /**
     * Get the notifications for the user.
     */
    public function notifications()
    {
        return $this->hasMany(Notification::class);
    }

    /**
     * Get unread notifications for the user.
     */
    public function unreadNotifications()
    {
        return $this->notifications()->where("is_read", false);
    }

    /**
     * Get the announcements created by the user.
     */
    public function announcements()
    {
        return $this->hasMany(Announcement::class, "created_by");
    }

    /**
     * Get the certificates generated by the user.
     */
    public function generatedCertificates()
    {
        return $this->hasMany(Certificate::class, "generated_by");
    }

    /**
     * Get the profile photo URL.
     *
     * @return string|null
     */
    public function getProfilePhotoUrlAttribute()
    {
        if ($this->profile_photo_path) {
            return asset("storage/" . $this->profile_photo_path);
        }

        return null;
    }
}
